apiVersion: v1
kind: Pod
metadata:
  name: user-task1
  labels:
    app: user-task1
spec:
  restartPolicy: OnFailure
  containers:
  - name: user-task1
    image: limitstory/stress_cpu:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: 1000Mi
      limits:
        memory: 1000Mi
      
