apiVersion: v1
kind: Pod
metadata:
  name: user-task2
  labels:
    app: user-task2
spec:
  restartPolicy: OnFailure
  containers:
  - name: user-task2
    image: limitstory/malloc:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: 1000Mi
      limits:
        memory: 10000Mi
      
